### ISSUE TITLE
Linuxsampler crashes after being connected with jsampler

### ISSUE THREAD

**Issue by senatoreg** [senatoreg/linuxsampler#3]
$ linuxsampler
LinuxSampler 2.0.0.svn41
Copyright (C) 2003,2004 by Benno Senoner and Christian Schoenebeck
Copyright (C) 2005-2017 Christian Schoenebeck
Binary built: Jan 18 2017
Detected features: MMX SSE SSE2
Automatic Stacktrace: Off
Creating Sampler...OK
Registered sampler engines: 'GIG','SF2','SFZ'
Registered MIDI input drivers: ALSA,JACK
Registered audio output drivers: ALSA,JACK
Loading instrument editor plugins...OK
Registered instrument editors: 'gigedit'
Registered internal effect systems: LADSPA
Could not scan LADSPA effects: library path '/home/gsenatore/.ladspa' doesn't exist
failed to load DLL: '/usr/lib/ladspa/gsm_1215.so', cause: /usr/lib/ladspa/gsm_1215.so: undefined symbol: gsm_destroy
Could not scan LADSPA effects: library path '/usr/local/lib/ladspa' doesn't exist
Registered internal effects: 334
Starting LSCP network server (0.0.0.0:8888)...OK
LinuxSampler initialization completed. :-)

LSCPServer: Client connection established on socket:8.
LSCPServer: Client connection established on socket:9.
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 11) > this->size() (which is 10)
Abort(coredump)
$ gdb /usr/bin/linuxsampler core 
GNU gdb (Debian 7.12-4) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/linuxsampler...done.
[New LWP 11013]
[New LWP 11012]
[New LWP 11011]
[New LWP 11010]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `linuxsampler'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fe769e09700 (LWP 11013))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007fe7688b440a in __GI_abort () at abort.c:89
#2  0x00007fe7693e704d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fe7693e5016 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fe7693e5061 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fe7693e5076 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fe7693e4cd2 in __cxa_call_unexpected () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fe76999a2a9 in LinuxSampler::AudioOutputDeviceFactory::GetDriverVersion (DriverName="ALSA") at AudioOutputDeviceFactory.cpp:224
#8  0x00007fe769881b67 in LinuxSampler::LSCPServer::GetAudioOutputDriverInfo (this=<optimized out>, Driver="ALSA") at lscpserver.cpp:1431
#9  0x00007fe7698595cf in yyparse (yyparse_param=yyparse_param@entry=0x7fe744000bb8) at lscp.y:390
#10 0x00007fe76988b3f4 in LinuxSampler::LSCPServer::Main (this=0x5555d8b51f50) at lscpserver.cpp:609
#11 0x00007fe7699da884 in LinuxSampler::__pthread_launcher (thread=0x5555d8b51f50) at Thread.cpp:402
#12 0x00007fe768c25464 in start_thread (arg=0x7fe769e09700) at pthread_create.c:333
#13 0x00007fe7689689df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
(gdb)

**Comment by senatoreg** [comment]
Fixed problem with SVN Macro conversion.
